version: "3.8"

services:
  web:
    image: acrscratch.azurecr.io/test/web:v1
    build: 
      context: .
      args:
          RUBY_VERSION: '2.6.6'
    command: ruby -rwebrick -e's=WEBrick::HTTPServer.new(:Port => 3000, :DocumentRoot => Dir.pwd).start'
    ports: 
      - '3021:3000'
    volumes:
      - data:/test
  
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
  
  redis:
    image: redis:6.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
  
  puppeteer:
    image: zenato/puppeteer-renderer
    ports:
      - 3000
        
volumes:
  redis:
  postgres:
  data:
